Separate e3kit pure sdk
VirgilSecurity/virgil pull request #15
Opened 2019-09-16 09:41 UTC by xlwknx

2019-09-17 14:45 UTC, cardoso requested changes

2019-09-17 14:45 UTC, cardoso commented on README.md
> +# E3kit Integrations
E3Kit

2019-09-17 14:45 UTC, cardoso commented on README.md
> +- [E3kit Integration](#E3Kit)
E3Kit

2019-09-17 14:45 UTC, cardoso commented on README.md
> +  * [Demo Web](https://github.com/cardoso/demo-e3kit-web)
https://github.com/VirgilSecurity/demo-e3kit-web

2019-09-18 11:43 UTC, MariiaMalitska approved these changes

2019-09-18 11:47 UTC, merged